import {Hono} from 'hono';
import {and,eq,sql} from 'drizzle-orm';
import {z} from 'zod';
import type {AppEnv} from '../config/env.ts';
import {readSessionCookie,verifySessionToken} from '../player/identity.ts';
import * as s from '../db/schema.ts';

type Options={db?:any;env:AppEnv;now?:()=>Date};const empty=z.object({}).strict();
function error(c:any,status:number,code:string,message:string){return c.json({error:{code,message}},status);}
export function createProgressionRoutes({db,env,now=()=>new Date()}:Options){
 const app=new Hono();app.use('*',async(c,next)=>{c.header('Cache-Control','no-store');await next();});async function player(c:any){if(!db||!env.SESSION_SECRET)return null;const session=verifySessionToken(readSessionCookie(c.req.header('cookie')),env.SESSION_SECRET,now());if(!session)return null;const [active]=await db.select({id:s.players.id}).from(s.players).where(and(eq(s.players.id,session.playerId),eq(s.players.status,'ACTIVE'))).limit(1);return active?session.playerId:null;}
 app.get('/achievements',async c=>{const playerId=await player(c);if(!playerId)return error(c,401,'UNAUTHENTICATED','Restore your account to view achievements.');const rows=await db.select({achievement:s.achievements,unlockedAt:s.playerAchievements.unlockedAt}).from(s.achievements).leftJoin(s.playerAchievements,and(eq(s.playerAchievements.achievementId,s.achievements.id),eq(s.playerAchievements.playerId,playerId))).where(eq(s.achievements.active,true));return c.json({achievements:rows.map((row:any)=>({...row.achievement,unlockedAt:row.unlockedAt}))});});
 app.get('/milestones',async c=>{const playerId=await player(c);if(!playerId)return error(c,401,'UNAUTHENTICATED','Restore your account to view milestones.');const rows=await db.select({milestone:s.milestones,reachedAt:s.playerMilestones.reachedAt}).from(s.milestones).leftJoin(s.playerMilestones,and(eq(s.playerMilestones.milestoneId,s.milestones.id),eq(s.playerMilestones.playerId,playerId))).where(eq(s.milestones.active,true));return c.json({milestones:rows.map((row:any)=>({...row.milestone,reachedAt:row.reachedAt}))});});
 app.get('/inventory',async c=>{const playerId=await player(c);if(!playerId)return error(c,401,'UNAUTHENTICATED','Restore your account to view inventory.');const [items,owned]=await Promise.all([db.select().from(s.inventoryItems).where(eq(s.inventoryItems.active,true)),db.select({itemId:s.playerInventory.itemId,unlockedAt:s.playerInventory.unlockedAt}).from(s.playerInventory).where(eq(s.playerInventory.playerId,playerId))]);const map=new Map(owned.map((row:any)=>[row.itemId,row.unlockedAt]));return c.json({items:items.map((item:any)=>({...item,unlockedAt:map.get(item.id)??null,owned:map.has(item.id)}))});});
 app.post('/inventory/:id/unlock',async c=>{const playerId=await player(c);if(!playerId)return error(c,401,'UNAUTHENTICATED','Restore your account to unlock an item.');if(!empty.safeParse(await c.req.json().catch(()=>({}))).success)return error(c,400,'INVALID_REQUEST','The inventory request is invalid.');const id=z.string().uuid().safeParse(c.req.param('id'));if(!id.success)return error(c,404,'ITEM_NOT_FOUND','This item is not available.');return db.transaction(async(tx:any)=>{const [item]=await tx.select().from(s.inventoryItems).where(and(eq(s.inventoryItems.id,id.data),eq(s.inventoryItems.active,true))).limit(1);if(!item)return error(c,404,'ITEM_NOT_FOUND','This item is not available.');const [owned]=await tx.select().from(s.playerInventory).where(and(eq(s.playerInventory.playerId,playerId),eq(s.playerInventory.itemId,item.id))).limit(1);if(owned)return c.json({unlocked:true,alreadyOwned:true});const [profile]=await tx.select().from(s.profiles).where(eq(s.profiles.playerId,playerId)).limit(1).for('update');if(!profile)return error(c,404,'PLAYER_NOT_FOUND','This player is not available.');if(profile.coins<item.priceCoins)return error(c,409,'INSUFFICIENT_COINS','You need more Coins to unlock this item.');await tx.update(s.profiles).set({coins:sql`${s.profiles.coins} - ${item.priceCoins}`,updatedAt:now()}).where(eq(s.profiles.playerId,playerId));await tx.insert(s.playerInventory).values({playerId,itemId:item.id,unlockedAt:now()}).onConflictDoNothing();if(item.priceCoins)await tx.insert(s.coinLedger).values({playerId,source:'inventory_purchase',amount:-item.priceCoins,referenceKey:item.key,createdAt:now()}).onConflictDoNothing();return c.json({unlocked:true,alreadyOwned:false,coins:profile.coins-item.priceCoins},201);});});
 app.post('/inventory/:id/equip',async c=>{const playerId=await player(c);if(!playerId)return error(c,401,'UNAUTHENTICATED','Restore your account to equip an item.');if(!empty.safeParse(await c.req.json().catch(()=>({}))).success)return error(c,400,'INVALID_REQUEST','The inventory request is invalid.');const id=z.string().uuid().safeParse(c.req.param('id'));if(!id.success)return error(c,404,'ITEM_NOT_FOUND','This item is not available.');return db.transaction(async(tx:any)=>{const [item]=await tx.select({id:s.inventoryItems.id,category:s.inventoryItems.category}).from(s.inventoryItems).innerJoin(s.playerInventory,eq(s.playerInventory.itemId,s.inventoryItems.id)).where(and(eq(s.inventoryItems.id,id.data),eq(s.playerInventory.playerId,playerId),eq(s.inventoryItems.active,true))).limit(1);if(!item)return error(c,404,'ITEM_NOT_OWNED','Unlock this item before equipping it.');const field:Record<string,string>={AVATAR:'avatarItemId',FRAME:'frameItemId',TITLE:'titleItemId',GRIMOIRE_SKIN:'grimoireSkinItemId',COMPANION_COSMETIC:'companionCosmeticItemId'},key=field[item.category];if(!key)return error(c,400,'INVALID_ITEM_CATEGORY','This item cannot be equipped.');await tx.update(s.profiles).set({[key]:item.id,updatedAt:now()}).where(eq(s.profiles.playerId,playerId));return c.json({equipped:true,itemId:item.id,category:item.category});});});
 return app;
}
