import {Hono} from 'hono';
import {and,eq,isNull,sql} from 'drizzle-orm';
import {z} from 'zod';
import webpush from 'web-push';
import type {AppEnv} from '../config/env.ts';
import {readSessionCookie,verifySessionToken} from '../player/identity.ts';
import {localDateAt,previousLocalDate} from '../config/game-rules.ts';
import * as s from '../db/schema.ts';

const subscriptionSchema=z.object({endpoint:z.string().url().max(2048),keys:z.object({p256dh:z.string().min(16).max(256),auth:z.string().min(8).max(256)}).strict()}).strict();
const removeSchema=z.object({endpoint:z.string().url().max(2048)}).strict();
type PushSender=(subscription:{endpoint:string;keys:{p256dh:string;auth:string}},payload:string)=>Promise<unknown>;
type Options={db?:any;env:AppEnv;now?:()=>Date;pushSender?:PushSender};
function error(c:any,status:number,code:string,message:string){return c.json({error:{code,message}},status);}
function validCron(c:any,env:AppEnv){return Boolean(env.CRON_SECRET&&c.req.header('authorization')===`Bearer ${env.CRON_SECRET}`);}
export function createNotificationRoutes({db,env,now=()=>new Date(),pushSender}:Options){
 const app=new Hono();app.use('*',async(c,next)=>{c.header('Cache-Control','no-store');await next();});
 const authenticate=async(c:any)=>{if(!db||!env.SESSION_SECRET)return null;const session=verifySessionToken(readSessionCookie(c.req.header('cookie')),env.SESSION_SECRET,now());if(!session)return null;const [player]=await db.select({id:s.players.id}).from(s.players).where(and(eq(s.players.id,session.playerId),eq(s.players.status,'ACTIVE'))).limit(1);return player?session.playerId:null;};
 app.get('/notifications/vapid-public-key',c=>env.VAPID_PUBLIC_KEY?c.json({publicKey:env.VAPID_PUBLIC_KEY}):error(c,503,'PUSH_UNAVAILABLE','Push reminders are not configured.'));
 app.post('/notifications/subscription',async c=>{const playerId=await authenticate(c);if(!playerId)return error(c,401,'UNAUTHENTICATED','Restore your account before enabling reminders.');const parsed=subscriptionSchema.safeParse(await c.req.json().catch(()=>null));if(!parsed.success)return error(c,400,'INVALID_SUBSCRIPTION','The push subscription is invalid.');const {endpoint,keys}=parsed.data,[existing]=await db.select({playerId:s.pushSubscriptions.playerId}).from(s.pushSubscriptions).where(eq(s.pushSubscriptions.endpoint,endpoint)).limit(1);if(existing&&existing.playerId!==playerId)return error(c,409,'SUBSCRIPTION_IN_USE','This browser subscription is linked to another player.');if(existing){await db.update(s.pushSubscriptions).set({p256dh:keys.p256dh,auth:keys.auth,disabledAt:null}).where(eq(s.pushSubscriptions.endpoint,endpoint));}else await db.insert(s.pushSubscriptions).values({playerId,endpoint,p256dh:keys.p256dh,auth:keys.auth,createdAt:now()});return c.json({subscribed:true},201);});
 app.delete('/notifications/subscription',async c=>{const playerId=await authenticate(c);if(!playerId)return error(c,401,'UNAUTHENTICATED','Restore your account before disabling reminders.');const parsed=removeSchema.safeParse(await c.req.json().catch(()=>null));if(!parsed.success)return error(c,400,'INVALID_SUBSCRIPTION','The push endpoint is invalid.');await db.update(s.pushSubscriptions).set({disabledAt:now()}).where(and(eq(s.pushSubscriptions.playerId,playerId),eq(s.pushSubscriptions.endpoint,parsed.data.endpoint),isNull(s.pushSubscriptions.disabledAt)));return c.json({subscribed:false});});
 app.get('/cron/daily-rollover',async c=>{if(!db)return error(c,503,'CRON_UNAVAILABLE','The database is not configured.');if(!validCron(c,env))return error(c,401,'CRON_UNAUTHORIZED','This scheduled job is not authorized.');const time=now(),profiles=await db.select().from(s.profiles);let updated=0;for(const profile of profiles){const today=localDateAt(time,profile.timezone||env.APP_TIMEZONE),yesterday=previousLocalDate(today),streak=profile.lastQuestCompletedDate&&profile.lastQuestCompletedDate>=yesterday?profile.streak:0,shouldReset=profile.dailyXpDate!==today||streak!==profile.streak;if(!shouldReset)continue;await db.update(s.profiles).set({dailyXpDate:today,dailyXp:profile.dailyXpDate===today?profile.dailyXp:0,streak,longestStreak:Math.max(profile.longestStreak,streak),updatedAt:time}).where(eq(s.profiles.playerId,profile.playerId));updated++;}return c.json({ok:true,updated,asOf:time.toISOString()});});
 app.get('/cron/morning-reminder',async c=>{if(!db)return error(c,503,'CRON_UNAVAILABLE','The database is not configured.');if(!validCron(c,env))return error(c,401,'CRON_UNAUTHORIZED','This scheduled job is not authorized.');if(!env.VAPID_PUBLIC_KEY||!env.VAPID_PRIVATE_KEY)return error(c,503,'PUSH_UNAVAILABLE','Push reminders are not configured.');const time=now(),sender=pushSender??(async(subscription,payload)=>{webpush.setVapidDetails(env.VAPID_SUBJECT,env.VAPID_PUBLIC_KEY!,env.VAPID_PRIVATE_KEY!);return webpush.sendNotification(subscription,payload);}),profiles=await db.select({playerId:s.profiles.playerId,timezone:s.profiles.timezone,lastQuestCompletedDate:s.profiles.lastQuestCompletedDate}).from(s.profiles).innerJoin(s.players,eq(s.players.id,s.profiles.playerId)).where(eq(s.players.status,'ACTIVE'));let sent=0,skipped=0,failed=0;
  for(const profile of profiles){const localDate=localDateAt(time,profile.timezone||env.APP_TIMEZONE);if(profile.lastQuestCompletedDate===localDate){skipped++;continue;}const [journey]=await db.select({id:s.journeys.id}).from(s.journeys).where(and(eq(s.journeys.playerId,profile.playerId),eq(s.journeys.status,'ACTIVE'))).limit(1);if(!journey){skipped++;continue;}const subscriptions=await db.select().from(s.pushSubscriptions).where(and(eq(s.pushSubscriptions.playerId,profile.playerId),isNull(s.pushSubscriptions.disabledAt)));if(!subscriptions.length){skipped++;continue;}const [notification]=await db.insert(s.notifications).values({playerId:profile.playerId,type:'MORNING_REMINDER',localDate,status:'PENDING',payloadJson:{title:'A little wiser, today?',body:'Your next small step is ready whenever you are.',url:'/\#today'},createdAt:time}).onConflictDoNothing().returning({id:s.notifications.id});if(!notification){skipped++;continue;}let delivered=false;for(const item of subscriptions){try{await sender({endpoint:item.endpoint,keys:{p256dh:item.p256dh,auth:item.auth}},JSON.stringify({title:'A little wiser, today?',body:'Your next small step is ready whenever you are.',url:'/\#today'}));delivered=true;await db.update(s.pushSubscriptions).set({lastSuccessAt:time}).where(eq(s.pushSubscriptions.id,item.id));}catch(reason){const status=Number((reason as any)?.statusCode)||0;if(status===404||status===410)await db.update(s.pushSubscriptions).set({disabledAt:time}).where(eq(s.pushSubscriptions.id,item.id));}}
   await db.update(s.notifications).set({status:delivered?'SENT':'FAILED',sentAt:delivered?time:null,...(delivered?{}:{error:'No push endpoint accepted this reminder.'})}).where(eq(s.notifications.id,notification.id));if(delivered)sent++;else failed++;
  }
  return c.json({ok:true,sent,skipped,failed,asOf:time.toISOString()});
 });
 return app;
}
