import {TRACKS,trackById} from './data.js';
import {icon,esc,btn,badge,sectionHead} from './ui.js';
export function draftCard(plan){return `<section class="draft-card"><div class="eyebrow red-text">${icon('compass')} A NEW ADVENTURE, WAITING FOR YOUR SEAL</div><h2>${esc(plan.title)}</h2><div class="meta">${badge(trackById(plan.trackId).name,'gold')}<span>${icon('clock')}${plan.minutes} min/day</span><span>${plan.days} estimated study days</span><span>${plan.experience==='beginner'?'Beginner friendly':'Build on the basics'}</span></div><div class="mini-roadmap">${plan.chapters.map((c,i)=>`<div><span>${i+1}</span><strong>${esc(c.title)}</strong><small>${esc(c.lane||'Study')} · ${c.topics?.length||0} concepts</small></div>`).join('')}</div><div class="button-row">${btn('Start this journey','activate',{icon:'flag',primary:true})}${btn('Inspect roadmap','preview-draft',{icon:'search'})}${btn('Start over','restart-chat',{class:'text-button'})}</div><p class="small-copy">Template-based demo · Your existing journeys and XP are preserved.</p></section>`;}
export function companionPage(s,busy=false){
  const stage=s.builder.stage;
  const prompts=stage==='experience'?['I am a beginner','I know the basics']:stage==='time'?['15 minutes a day','30 minutes a day','60 minutes a day']:['I want to learn Java','Prepare for coding interviews','Master OOP fundamentals','Learn Python','Learn JavaScript','Learn AI and machine learning','Build a PDF chatbot','Learn ESP32','Explore Xiaozhi','Practice IELTS','Learn badminton','Explore psychology'];
  return `${sectionHead('ARCANA / YOUR COMPANION IN CURIOSITY','A conversation. A new chapter.','Tell Arcana what you want to learn. Shape a journey around your life.',badge('Simulated companion','sample'))}
  <div class="chat-layout"><section class="paper chat-panel"><div class="chat-topline"><span class="companion-avatar">${icon('spark')}</span><div><strong>Arcana</strong><small>Your guide through the grand archives</small></div><span class="chat-online"><i></i> Ready to explore</span><button class="icon-button" data-action="restart-chat" aria-label="Start a new roadmap conversation">${icon('plus')}</button></div>
  <div class="chat-transcript" id="chat-transcript" role="log" aria-label="Conversation with Arcana" aria-live="polite">${s.messages.map((m,i)=>`<div class="message ${m.role}"><div class="message-by">${m.role==='assistant'?`${icon('spark')} Arcana`:'Minh'}<span>${m.role==='assistant'?'Demo response':'You'}</span></div><div class="message-bubble">${esc(m.text).replace(/\n/g,'<br>')}${m.kind==='draft'&&s.draft&&i===s.messages.map(x=>x.kind).lastIndexOf('draft')?draftCard(s.draft):''}${m.kind==='proposal'&&s.proposal?`<div class="inline-proposal"><strong>${s.proposal.previous} → ${s.proposal.minutes} minutes / day</strong><p>A proposed change. You decide when it takes effect.</p>${btn('Review changes','proposal',{primary:true,icon:'arrow'})}</div>`:''}</div></div>`).join('')}${busy?'<div class="typing" role="status">Arcana is opening a new page <span>•••</span></div>':''}</div>
  <div class="chat-input-area"><div class="prompt-label">${icon('spark')} A LITTLE INSPIRATION</div><div class="prompt-chips">${prompts.map(p=>`<button data-action="prompt" data-id="${esc(p)}" ${busy?'disabled':''}>${esc(p)}</button>`).join('')}</div><form id="chat-form"><label class="sr-only" for="chat-input">Message Arcana</label><textarea id="chat-input" name="message" placeholder="Tell Arcana what you would like to learn…" rows="2" maxlength="1600" required ${busy?'disabled':''}></textarea><div class="composer-bottom"><small>Enter to send · Shift + Enter for a new line</small><button type="submit" class="btn primary" ${busy?'disabled':''}>${icon('send')} Send message</button></div></form><p class="chat-disclaimer">Prepared scenarios · No live AI · Your roadmap starts only when you confirm.</p></div></section>
  <aside class="chat-aside"><section class="paper companion-profile"><div class="companion-illustration"><img src="/assets/library.png" alt="Arcana, your friendly book companion"></div><div class="eyebrow">A GUIDE, NOT A GATEKEEPER</div><h2>One step at a time.</h2><p>Big ambitions begin with small, thoughtful plans. Let's find your starting point.</p><ol class="builder-steps">${['Choose your destination','Share your starting point','Find your daily rhythm','Review & begin'].map((x,i)=>`<li class="${i===({goal:0,experience:1,time:2,ready:3}[stage]||0)?'current':''}"><span>${i+1}</span>${x}</li>`).join('')}</ol></section><section class="paper chat-topics"><div class="eyebrow">EXPLORE ALL ${TRACKS.length} ARTS</div>${TRACKS.map(t=>`<button data-action="start-track" data-id="${t.id}" ${busy?'disabled':''}><span style="color:${t.color}">${icon(t.icon)}</span>${esc(t.name)}${icon('chevron')}</button>`).join('')}</section><div class="margin-note">${icon('shield')} You set the pace. No exams, no lost ranks, and no pressure to keep a streak.</div></aside></div>`;
}
