import {getCampaignChapters,getQuestsForCampaign} from './demo-quests.js';

export function createPlannerState(){return {status:'IDLE',step:'CAREER',messages:[],answers:{careerId:null,experience:null,goal:'',dailyMinutes:30},proposal:null,origin:'today'};}
const prompts={CAREER:'What career are you working toward?',STARTING_POINT:'What have you already worked with?',GOAL:'What would you like to be able to do confidently?',TIME:'How much time can you spend each day?'};
export function startPlanner(state=createPlannerState(),origin='today'){return {...structuredClone(state),status:'COLLECTING',step:'CAREER',origin,messages:[{role:'assistant',text:prompts.CAREER}]};}
export function answerPlannerStep(state,value){const next=structuredClone(state);const text=String(value||'').trim();if(!text)return next;if(next.step==='CAREER'){next.answers.careerId=typeof value==='string'&&['backend-developer','ux-researcher','product-marketing-manager'].includes(value)?value:'backend-developer';next.step='STARTING_POINT';next.messages.push({role:'user',text:text},{role:'assistant',text:prompts.STARTING_POINT});}else if(next.step==='STARTING_POINT'){next.answers.experience=text;next.step='GOAL';next.messages.push({role:'user',text},{role:'assistant',text:prompts.GOAL});}else if(next.step==='GOAL'){next.answers.goal=text;next.step='TIME';next.messages.push({role:'user',text},{role:'assistant',text:prompts.TIME});}else if(next.step==='TIME'){next.answers.dailyMinutes=Number(value)||30;next.step='TIME';next.status='COLLECTING';next.messages.push({role:'user',text},{role:'assistant',text:'I found a likely starting point. I’ll preserve what you already know, verify uncertain skills, and focus your campaign on the gaps that matter.'});}return next;}
export function buildCampaignProposal(state){const careerId=state.answers.careerId||'backend-developer';const chapters=getCampaignChapters(careerId).map(chapter=>({...chapter,quests:chapter.questIds.map(id=>getQuestsForCampaign(careerId).find(quest=>quest.id===id)).filter(Boolean)}));const proposal={careerId,title:`${careerId==='backend-developer'?'Backend Developer':careerId==='ux-researcher'?'UX Researcher':'Product Marketing Manager'} Campaign`,goal:state.answers.goal||'Build production-ready skills for the target career.',dailyMinutes:state.answers.dailyMinutes||30,estimatedWeeks:6,chapters,bossQuestId:careerId==='backend-developer'?'backend-secure-rest-api':careerId==='ux-researcher'?'ux-run-usability-study':'pmm-go-to-market-brief'};return {...state,status:'PREVIEW',proposal};}
export function acceptCampaignProposal(state){if(!state.proposal)return state;return {...structuredClone(state),status:'ACCEPTED'};}
export function resetPlanner(){return createPlannerState();}
