const lightQuests=[
 {id:'ux-researcher-interview-plan',chapterId:'ux-discovery',title:'Plan a User Interview',type:'LEARN',status:'RECOMMENDED',minutes:20,skills:['skill-user-research'],why:'Turn a product question into a focused research plan.',assignment:{instructions:'Write a research question, participant profile, and three interview prompts.',items:['Question','Participant','Prompts']},submission:{type:'TEXT',required:true},rubric:['Clear question','Relevant participant','Open prompts'],expectedEvidence:'APPLIED',prerequisites:[],completionEffect:{stateTransition:'APPLY_RESEARCH'}},
 {id:'ux-researcher-usability-study',chapterId:'ux-validation',title:'Run a Usability Study',type:'APPLIED_TRIAL',status:'AVAILABLE',minutes:30,skills:['skill-usability-testing'],why:'Practice observing behavior and turning notes into product insights.',assignment:{instructions:'Describe a five-task usability study and the evidence you would capture.',items:['Tasks','Observation notes','Insight']},submission:{type:'TEXT',required:true},rubric:['Task clarity','Evidence quality','Insight'],expectedEvidence:'APPLIED',prerequisites:['ux-researcher-interview-plan'],completionEffect:{stateTransition:'APPLY_RESEARCH'}},
 {id:'ux-run-usability-study',chapterId:'ux-validation',title:'Synthesize Research Findings',type:'BOSS',status:'LOCKED',minutes:45,skills:['skill-user-research','skill-usability-testing'],why:'Bring discovery and validation together in a decision-ready research readout.',assignment:{instructions:'Submit a concise readout with themes, evidence, and one product recommendation.',items:['Themes','Evidence','Recommendation']},submission:{type:'PROJECT_NOTE',required:true},rubric:['Themes · 35%','Evidence · 35%','Recommendation · 30%'],expectedEvidence:'APPLIED',prerequisites:['ux-researcher-usability-study'],completionEffect:{stateTransition:'COMPLETE_BOSS'}},
 {id:'pmm-positioning-foundations',chapterId:'pmm-strategy',title:'Positioning Foundations',type:'LEARN',status:'RECOMMENDED',minutes:20,skills:['skill-positioning'],why:'Clarify the audience, problem, and promise before planning a launch.',assignment:{instructions:'Draft a positioning statement for one target segment.',items:['Audience','Problem','Promise']},submission:{type:'TEXT',required:true},rubric:['Audience','Problem','Promise'],expectedEvidence:'APPLIED',prerequisites:[],completionEffect:{stateTransition:'APPLY_POSITIONING'}},
 {id:'pmm-launch-message',chapterId:'pmm-activation',title:'Write a Launch Message',type:'PRACTICE',status:'AVAILABLE',minutes:25,skills:['skill-messaging'],why:'Practice translating product value into a clear campaign message.',assignment:{instructions:'Write a headline, proof point, and call to action for a launch.',items:['Headline','Proof','CTA']},submission:{type:'TEXT',required:true},rubric:['Clarity','Proof','CTA'],expectedEvidence:'ASSESSED',prerequisites:['pmm-positioning-foundations'],completionEffect:{stateTransition:'ASSESS_MESSAGING'}},
 {id:'pmm-go-to-market-brief',chapterId:'pmm-activation',title:'Build a Go-to-Market Brief',type:'BOSS',status:'LOCKED',minutes:45,skills:['skill-positioning','skill-messaging'],why:'Combine positioning and messaging into a launch-ready brief.',assignment:{instructions:'Submit a one-page brief covering audience, channel, message, and measurement.',items:['Audience','Channel','Message','Metric']},submission:{type:'PROJECT_NOTE',required:true},rubric:['Audience · 25%','Channel · 25%','Message · 25%','Measurement · 25%'],expectedEvidence:'APPLIED',prerequisites:['pmm-launch-message'],completionEffect:{stateTransition:'COMPLETE_BOSS'}}
];

const backendQuests=[
 {id:'backend-java-foundations',chapterId:'programming-foundations',title:'Java Foundations',type:'LEARN',status:'COMPLETED',minutes:20,skills:['skill-java'],why:'Java is an existing strength preserved in your campaign.',assignment:{instructions:'Review classes, interfaces, and exception handling in a small backend example.',items:['Read the short lesson','Mark the resource reviewed']},submission:{type:'CHECKLIST',required:false},expectedEvidence:'NONE',prerequisites:[],completionEffect:{stateTransition:'NO_MASTERY_CHANGE'}},
 {id:'backend-http-foundations',chapterId:'programming-foundations',title:'HTTP Foundations',type:'PRACTICE',status:'COMPLETED',minutes:20,skills:['skill-http'],why:'HTTP supports every backend API decision that follows.',assignment:{instructions:'Identify the method, status code, and body for three HTTP scenarios.',items:['Review three scenarios','Choose the response']},submission:{type:'QUIZ',required:true},expectedEvidence:'ASSESSED',prerequisites:[],completionEffect:{stateTransition:'ASSESS_HTTP'}},
 {id:'backend-rest-skill-check',chapterId:'backend-core',title:'REST API Skill Check',type:'SKILL_CHECK',status:'AVAILABLE',minutes:10,skills:['skill-rest-api'],why:'Validate REST API evidence before moving to a larger implementation task.',assignment:{instructions:'Answer three questions about resources, methods, and status codes.',items:['Answer all questions','Submit the check']},submission:{type:'QUIZ',required:true},expectedEvidence:'ASSESSED',prerequisites:['backend-http-foundations'],completionEffect:{stateTransition:'ASSESS_REST'}},
 {id:'backend-rest-endpoint',chapterId:'backend-core',title:'Build a REST Endpoint',type:'APPLIED_TRIAL',status:'LOCKED',minutes:30,skills:['skill-rest-api'],why:'Apply REST API design in a small implementation.',assignment:{instructions:'Design a resource endpoint and explain its request and response shape.',items:['Endpoint design','Validation behavior','One failure case']},submission:{type:'TEXT',required:true},expectedEvidence:'APPLIED',prerequisites:['backend-rest-skill-check'],completionEffect:{stateTransition:'APPLY_REST'}},
 {id:'backend-sql-practice',chapterId:'data-persistence',title:'SQL Practice',type:'PRACTICE',status:'AVAILABLE',minutes:20,skills:['skill-sql'],why:'Practice keeps your existing SQL evidence usable in backend work.',assignment:{instructions:'Review three queries and identify joins, filters, and safe parameter handling.',items:['Review the queries','Submit your choices']},submission:{type:'QUIZ',required:true},expectedEvidence:'ASSESSED',prerequisites:[],completionEffect:{stateTransition:'ASSESS_SQL'}},
 {id:'backend-sql-recall',chapterId:'data-persistence',title:'SQL Recall',type:'RECALL',status:'AVAILABLE',minutes:12,skills:['skill-sql'],why:'Your SQL evidence is strong but can become stale.',assignment:{instructions:'Answer three short SQL recall prompts.',items:['Recall a join','Recall NULL handling','Recall a safe parameter']},submission:{type:'QUIZ',required:true},expectedEvidence:'NONE',prerequisites:[],completionEffect:{stateTransition:'REFRESH_SQL'}},
 {id:'backend-auth-skill-check',chapterId:'security-testing',title:'Authentication Skill Check',type:'SKILL_CHECK',status:'RECOMMENDED',minutes:10,skills:['skill-authentication'],why:'LifeOS needs stronger evidence before deciding whether you should review or apply authentication.',scenario:'Answer three questions about identity, authorization, and expired tokens.',assignment:{instructions:'Choose the best answer for each authentication scenario.',items:['What is authentication primarily responsible for?','Are authentication and authorization the same?','What should an API do with an expired token?']},submission:{type:'QUIZ',required:true},rubric:['Identity verification','Authentication vs authorization','Expired token handling'],expectedEvidence:'ASSESSED',prerequisites:['backend-rest-skill-check'],completionEffect:{stateTransition:'ASSESS_AUTHENTICATION'}},
 {id:'backend-jwt-applied-trial',chapterId:'security-testing',title:'Implement JWT Authentication',type:'APPLIED_TRIAL',status:'LOCKED',minutes:30,skills:['skill-authentication'],why:'Apply authentication after the Skill Check reduces uncertainty.',scenario:'You are building a REST API for a student project. Users must log in and access a protected profile route.',assignment:{instructions:'Design the login flow, token validation, and one failure case.',items:['POST /login','GET /profile requires a valid token','Handle an invalid or expired token','Explain one test']},submission:{type:'TEXT',required:true},rubric:['Authentication flow','Token handling','Failure handling','Explanation'],expectedEvidence:'APPLIED',prerequisites:['backend-auth-skill-check'],completionEffect:{stateTransition:'APPLY_AUTHENTICATION'}},
 {id:'backend-api-error-practice',chapterId:'security-testing',title:'API Error Handling Practice',type:'PRACTICE',status:'AVAILABLE',minutes:20,skills:['skill-testing'],why:'Practice gives Testing an evaluated signal without claiming Applied mastery.',assignment:{instructions:'Review three API responses and choose the correct status code and behavior.',items:['Scenario one','Scenario two','Scenario three']},submission:{type:'QUIZ',required:true},expectedEvidence:'ASSESSED',prerequisites:[],completionEffect:{stateTransition:'ASSESS_TESTING'}},
 {id:'backend-docker-fundamentals',chapterId:'production',title:'Docker Fundamentals',type:'LEARN',status:'AVAILABLE',minutes:25,skills:['skill-docker'],why:'Docker is a current gap and this is the smallest useful entry point.',assignment:{instructions:'Review what containers solve, image vs container, Dockerfile basics, and Compose basics.',items:['Open the resource','Mark resource reviewed']},submission:{type:'CHECKLIST',required:false},expectedEvidence:'NONE',prerequisites:[],completionEffect:{stateTransition:'LEARN_DOCKER'}},
 {id:'backend-containerize-api',chapterId:'production',title:'Containerize the API',type:'APPLIED_TRIAL',status:'LOCKED',minutes:30,skills:['skill-docker'],why:'Build evidence after learning Docker fundamentals.',assignment:{instructions:'Describe a Dockerfile and Compose setup for the API.',items:['Image choice','Port mapping','Environment configuration']},submission:{type:'TEXT',required:true},expectedEvidence:'APPLIED',prerequisites:['backend-docker-fundamentals'],completionEffect:{stateTransition:'APPLY_DOCKER'}},
 {id:'backend-secure-rest-api',chapterId:'boss',title:'Secure a REST API',type:'BOSS',status:'LOCKED',minutes:45,skills:['skill-rest-api','skill-sql','skill-authentication','skill-testing'],why:'Validate several backend skills together in one realistic assignment.',assignment:{instructions:'Submit an API design, authentication flow, authorization rule, SQL interaction, tests, and architecture explanation.',items:['API endpoint structure','Login / JWT authentication','Protected route','Authorization rule','Persistence / SQL interaction','Tests','Architecture explanation']},submission:{type:'PROJECT_NOTE',required:true},rubric:['REST API design · 20%','Authentication · 25%','Authorization · 15%','Data handling · 15%','Testing · 15%','Technical explanation · 10%'],expectedEvidence:'APPLIED',prerequisites:['backend-jwt-applied-trial','backend-api-error-practice'],completionEffect:{stateTransition:'COMPLETE_BOSS'}}
];

const chapterMeta=[
 {id:'programming-foundations',title:'Programming Foundations',objective:'Preserve the foundations already supporting backend work.',questIds:['backend-java-foundations','backend-http-foundations']},
 {id:'backend-core',title:'Backend Core',objective:'Design and validate production-ready API boundaries.',questIds:['backend-rest-skill-check','backend-rest-endpoint']},
 {id:'data-persistence',title:'Data & Persistence',objective:'Keep data handling reliable and observable.',questIds:['backend-sql-practice','backend-sql-recall']},
 {id:'security-testing',title:'Security & Testing',objective:'Turn uncertain authentication and testing signals into evidence.',questIds:['backend-auth-skill-check','backend-jwt-applied-trial','backend-api-error-practice']},
 {id:'production',title:'Production',objective:'Move the API toward repeatable delivery.',questIds:['backend-docker-fundamentals','backend-containerize-api']}
];

const lightChapters={
 'ux-researcher':[{id:'ux-discovery',title:'Discovery',objective:'Frame the research question and prepare the interview.',questIds:['ux-researcher-interview-plan']},{id:'ux-validation',title:'Validation',objective:'Run and synthesize a small usability study.',questIds:['ux-researcher-usability-study','ux-run-usability-study']}],
 'product-marketing-manager':[{id:'pmm-strategy',title:'Positioning',objective:'Define the audience and value proposition.',questIds:['pmm-positioning-foundations']},{id:'pmm-activation',title:'Activation',objective:'Turn the message into a measurable launch brief.',questIds:['pmm-launch-message','pmm-go-to-market-brief']}]
};
const allQuests=[...backendQuests,...lightQuests];
export function getQuestById(id){return allQuests.find(quest=>quest.id===id);}
export function getQuestsForCampaign(careerId='backend-developer'){return structuredClone(careerId==='backend-developer'?backendQuests:lightQuests.filter(quest=>quest.id.startsWith(careerId.replace('product-marketing-manager','pmm'))));}
export function getCampaignChapters(careerId='backend-developer'){return structuredClone(careerId==='backend-developer'?chapterMeta:lightChapters[careerId]||[]);}
export function getQuestRequirements(id){return getQuestById(id)?.assignment||null;}
export function getQuestRubric(id){return getQuestById(id)?.rubric||[];}
export function getDemoSubmission(id){const quest=getQuestById(id);if(!quest)return null;return quest.type==='SKILL_CHECK'?{answers:[]} : quest.type==='BOSS'?{summary:'The API validates identity, protects the profile route, handles authorization, persists data safely, and includes tests.',decision:'I kept authentication and authorization separate.',verification:'I verified success, invalid token, and forbidden access cases.'}:{summary:'Demo submission prepared for presentation.',failureCase:'Invalid input returns a clear error.',verification:'I reviewed the expected behavior against the assignment.'};}
