import {TRACKS,trackById,STATUSES} from './data.js';
import {activeJourney,levelFor} from './state.js';
import {icon,esc,btn,badge,sectionHead,progress} from './ui.js';
import {knowledgeGraph,roadmapGraph} from './graph.js';

export function questCard(q){return `<article class="quest-card ${q.status}"><div class="quest-rune">${icon(q.status==='completed'?'check':q.type==='Learn'?'book':'code')}</div><div class="quest-copy"><div class="meta">${badge(q.type,q.type==='Practice'?'red':'')}${badge(`Rank ${q.difficulty}`,'gold')}<span>${icon('clock')}${q.minutes} min</span><span class="xp-text">+${q.xp} XP</span>${q.status==='in-progress'?'<span class="red-text">● In progress</span>':''}</div><h3>${esc(q.title)}</h3><p>${esc(q.description)}</p></div><div class="quest-action">${btn(q.status==='completed'?'View completed':q.status==='in-progress'?'Continue Quest':'Begin Quest','quest',{id:q.id,primary:q.status==='in-progress',icon:q.status==='completed'?'check':'arrow'})}</div></article>`;}

export function todayPage(s){
  const j=activeJourney(s);
  if(!j)return `${sectionHead('LIFEOS ACADEMY / TODAY','A fresh page','Pick a field to explore. Your first roadmap begins with one small step.',badge('No active journey','gold'))}<section class="paper empty-state"><span class="detail-emblem">${icon('compass')}</span><h2>Your next adventure is waiting.</h2><p>Choose a subject and set a pace that fits your day. You can explore the curriculum before you begin.</p>${btn('Begin a new journey','new-journey',{icon:'flag',primary:true})}</section>`;
  const server=s.mode==='server',name=s.profile?.displayName||'Minh',qs=s.quests.filter(q=>q.journeyId===j.id),done=qs.filter(q=>q.status==='completed'),next=j.status==='completed'?null:qs.find(q=>q.status!=='completed');
  const budget=j.minutes;let used=0;const today=[];
  for(const q of qs.filter(q=>j.status!=='completed'&&q.status!=='completed')){if(used+q.minutes<=budget||!today.length){today.push(q);used+=q.minutes;}}
  const shown=[...(done.length?[done.at(-1)]:[]),...today];
  return `<div class="goal-strip"><span class="eyebrow">${icon('flag')} CURRENT GOAL</span><strong>${esc(j.title)}</strong>${badge(server?'Account journey':'Sample data',server?'green':'sample')}<span class="goal-version">Vol. ${String(j.version).padStart(2,'0')}</span></div>
  <section class="hero paper"><div class="hero-copy"><div class="eyebrow red-text">${icon('book')} A NEW PAGE IN YOUR STORY</div><h1>Every small step<br>awakens a new branch<br>of knowledge.</h1><p>Welcome back, ${esc(name)}. A little curiosity, a little practice.<br class="desktop-only"> Your next adventure is waiting in the grand archives.</p><div class="button-row">${next?btn('Continue Quest','quest',{id:next.id,primary:true,icon:'flame'}):j.status==='completed'?btn('Begin a new journey','new-journey',{icon:'flag',primary:true}):btn('Reflect on your journey','finish-journey',{icon:'flag',primary:true})}${btn('Open Roadmap','navigate',{id:'roadmap',icon:'compass'})}</div><div class="hero-footnote">${icon('leaf')} Grow at your own pace. Every chapter counts.</div></div><div class="hero-art"><img src="/assets/library.png" alt="An illuminated knowledge tree in a magical library, with a friendly grimoire companion"><div class="art-caption"><span>✦ The Grand Archives</span><span>EST. MMXXVI</span></div></div></section>
  <div class="stats-grid"><section class="paper stat-card"><div class="stat-head"><span class="eyebrow">CHARACTER JOURNEY</span>${icon('trophy')}</div><div class="stat-number">${levelFor(s.xp)}<span>LEVEL<br><small>Apprentice Scribe</small></span><strong>${s.xp}<small>TOTAL XP</small></strong></div>${progress(s.xp%100)}<div class="stat-caption"><span>Activity brings experience</span><b>${100-s.xp%100} XP to Level ${levelFor(s.xp)+1}</b></div></section>
  <section class="paper stat-card"><div class="stat-head"><span class="eyebrow">${s.preferences.streak?'A LITTLE, EVERY DAY':'YOUR OWN RHYTHM'}</span>${icon(s.preferences.streak?'flame':'leaf')}</div><div class="stat-number">${s.preferences.streak?(server?s.progress.streak:7):'∞'}<span>${s.preferences.streak?'DAY STREAK':'POSSIBILITIES'}<br><small>${s.preferences.streak?(server?'Current account streak':'A week of small victories · sample'):'Learning has no finish line'}</small></span>${badge(server?'Keep growing':'Keep growing','green')}</div>${server?'<div class="evidence-preview">Your streak is calculated from completed activities.</div>':`<div class="week-strip">${['M','T','W','T','F','S','S'].map((d,i)=>`<span class="${i===6?'current':''}">${d}<b>${i===6?'✦':'✓'}</b></span>`).join('')}</div>`}</section></div>
  <section class="domain-section"><div class="section-title"><div><div class="eyebrow">${TRACKS.length} PATHS. ENDLESS POSSIBILITIES.</div><h2>Choose your next discovery</h2></div>${btn('Explore all branches','navigate',{id:'knowledge',icon:'tree',class:'text-button'})}</div><div class="domain-grid">${TRACKS.map(t=>`<button class="domain-card" data-action="start-track" data-id="${t.id}" style="--domain-color:${t.color}"><span class="domain-icon">${icon(t.icon)}</span><strong>${esc(t.name)}</strong><small>${esc(t.subtitle)}</small><span class="domain-bottom">${t.concepts.length} concepts ${icon('arrow')}</span></button>`).join('')}</div></section>
  <section><div class="section-title quest-heading"><div><div class="eyebrow">YOUR DAILY CHAPTER</div><h2>${icon("code")} ${j.status==="completed"?"Journey complete":"Today's Quests"}</h2><p>${s.restDay?'A quieter page today. Your progress is safe.':`${used} min planned · ${done.length} of ${qs.length} journey activities complete`}</p></div><div class="button-row">${btn(s.restDay?'Resume today':'Take a rest day','rest',{icon:'moon',class:'small'})}${btn('Adjust pace','schedule',{icon:'settings',class:'small'})}</div></div>${s.restDay?`<div class="paper empty-state">${icon('leaf')}<h3>Rest is part of the journey.</h3><p>Your XP, knowledge, and personal ranks stay with you.</p>${btn('Return to my quests','rest',{primary:true})}</div>`:`<div class="quest-list">${shown.map(questCard).join('')}</div>`}</section>
  <aside class="wisdom"><span class="wisdom-icon">✧</span><div><div class="eyebrow">A NOTE FROM YOUR COMPANION</div><p>“You do not need to master the whole forest today. Get to know one leaf.”</p></div>${btn('Talk to Arcana','navigate',{id:'companion',icon:'arrow',class:'text-button'})}</aside>`;
}
export const graphToolbar=(view)=>`<div class="segmented"><button data-action="view" data-id="graph" class="${view==='graph'?'active':''}">${icon('tree')} Node Graph</button><button data-action="view" data-id="list" class="${view==='list'?'active':''}">${icon('list')} List View</button></div><div class="zoom-controls"><button aria-label="Zoom in" data-zoom="in">${icon('plus')}</button><button aria-label="Zoom out" data-zoom="out">${icon('minus')}</button><button aria-label="Fit graph to screen" data-zoom="fit">${icon('fit')}</button></div>`;
export function conceptDetail(c){
  const st=STATUSES[c.status],t=trackById(c.trackId);
  const domainIcon=t?.icon||c.domainIcon||'tree';
  return `<div class="detail-title"><span class="eyebrow">${icon(domainIcon)} ${esc(c.domainName||t?.name||'KNOWLEDGE')} · CONCEPT</span>${badge(c.serverBacked?'Account progress':'Sample evidence',c.serverBacked?'green':'sample')}</div><div class="detail-emblem" style="color:${st.color}">${icon(domainIcon)}</div><h2>${esc(c.name)}</h2>${badge(st.label,c.status==='applying'||c.status==='mastered'?'green':'')}<p>${esc(c.scope)}</p><div class="thin-rule"></div><div class="eyebrow">SOURCE & CONTEXT</div><p class="small-copy">${c.serverBacked?'This knowledge level is from your account. Private evidence details are not shown here.':c.status==='self'?'A self-reported starting point. This is separate from observed understanding.':c.status==='unobserved'?'No observations yet. This does not mean you do not know the topic.':'Illustrative signals from sample conversations. These are not a certificate of proficiency.'}</p>${c.serverBacked?'<div class="evidence-preview">Your account knowledge state · private evidence stays private.</div>':c.evidence.length?`<div class="evidence-preview">${icon('book')} ${c.evidence.length} sample conversations<span>Last observed Sep 24, 2026</span></div>`:'<div class="evidence-preview">An unwritten page, ready to explore.</div>'}<div class="stack-buttons">${btn(c.serverBacked?'Knowledge details':'Inspect evidence','evidence',{id:c.id,icon:'search'})}${btn('Learn this branch','start-track',{id:c.trackId,icon:'arrow',primary:true})}</div>`;
}
export function knowledgePage(s,v){
  const domains=s.domains?.length?s.domains:TRACKS.map(t=>({id:t.id,name:t.name,icon:t.icon,color:t.color}));
  const filtered=s.concepts.filter(c=>(v.track==='all'||c.trackId===v.track)&&(v.filter==='all'||c.status===v.filter)&&c.name.toLowerCase().includes(v.search.toLowerCase()));
  const selected=s.concepts.find(c=>c.id===v.concept)||s.concepts.find(c=>c.trackId===(v.track==='all'?'python':v.track));
  return `${sectionHead('GRAND ARCHIVES / THE LIVING KNOWLEDGE TREE','My Knowledge','A growing map of what you have explored, connected, and put into practice.',badge(`${s.concepts.length} concepts · ${domains.length} branches`,'gold'))}
  <div class="branch-tabs"><button data-action="branch" data-id="all" class="${v.track==='all'?'active':''}">${icon('tree')} All branches</button>${domains.map(domain=>`<button data-action="branch" data-id="${esc(domain.id)}" class="${v.track===domain.id?'active':''}">${icon(domain.icon||'tree')} ${esc(domain.name)}</button>`).join('')}</div>
  <div class="graph-layout expansive-layout"><section class="paper graph-panel"><div class="graph-tools">${graphToolbar(v.view)}</div><div class="graph-filters"><label class="search-input">${icon('search')}<input id="concept-search" type="search" aria-label="Search concepts" placeholder="Search concepts, sigils..." value="${esc(v.search)}"></label><select id="status-filter" aria-label="Filter concepts by status"><option value="all">All observations</option>${Object.entries(STATUSES).map(([k,st])=>`<option value="${k}" ${v.filter===k?'selected':''}>${st.label}</option>`).join('')}</select></div>${v.view==='graph'?knowledgeGraph(s.concepts,{track:v.track,search:v.search,filter:v.filter,selected:v.concept,page:v.conceptPage||0,domains}):`<div class="concept-list">${filtered.length?filtered.map(c=>`<button data-action="concept" data-id="${c.id}" class="concept-row ${v.concept===c.id?'selected':''}"><span class="status-dot" style="background:${STATUSES[c.status].color}"></span><strong>${esc(c.name)}</strong><span>${STATUSES[c.status].short}</span>${icon('chevron')}</button>`).join(''):'<div class="empty-state"><h3>No concepts found</h3><p>Try another search or filter.</p></div>'}</div>`}<div class="graph-pagination"><span>${filtered.length} concepts ${!v.search&&v.filter==='all'?'· All nodes visible · Zoom to explore':`· Page ${Math.min(v.conceptPage||0,Math.max(0,Math.ceil(filtered.length/6)-1))+1} of ${Math.max(1,Math.ceil(filtered.length/6))}`}</span>${v.view==='graph'&&(v.search||v.filter!=='all')?`<div>${btn('Previous','concept-page',{id:String(Math.max(0,(v.conceptPage||0)-1)),disabled:!(v.conceptPage>0),class:'small'})}${btn('Next concepts','concept-page',{id:String((v.conceptPage||0)+1),disabled:((v.conceptPage||0)+1)*6>=filtered.length,class:'small'})}</div>`:''}</div><div class="graph-legend">${Object.entries(STATUSES).map(([k,st])=>`<span><i style="background:${st.color}"></i>${st.short}</span>`).join('')}</div></section><aside class="detail-column"><section class="paper dossier" id="concept-dossier">${conceptDetail(selected)}</section><div class="margin-note">${icon('info')} Learning is a journey, not a score. XP and personal ranks tell different stories.</div></aside></div>`;
}
export function roadmapPage(s,v){
  const sample=Boolean(v.examplePlan),j=v.examplePlan||activeJourney(s);
  if(!j)return `${sectionHead('LEYLINES & CHRONICLES / YOUR EXPEDITION MAP','Roadmap & Expedition','Small steps, connected into a journey worth taking.',btn('New journey','new-journey',{icon:'plus',primary:true}))}<section class="paper empty-state"><span class="detail-emblem">${icon('tree')}</span><h2>Your roadmap will grow here.</h2><p>Ask Arcana to shape a learning path, or start from one of the ${TRACKS.length} detailed curriculum templates.</p>${btn('Create a journey','new-journey',{icon:'flag',primary:true})}</section>`;
  const qs=sample?j.chapters.flatMap(c=>c.quests):s.quests.filter(q=>q.journeyId===j.id),ci=Math.min(v.chapter,j.chapters.length-1),c=j.chapters[ci],cqs=qs.filter(q=>q.chapter===ci),done=qs.filter(q=>q.status==='completed').length;
  return `${sectionHead('LEYS & CHRONICLES / YOUR EXPEDITION MAP','Roadmap & Expedition','Small steps, connected into a journey worth taking.',btn('New journey','new-journey',{icon:'plus',primary:true}))}
  <section class="sample-browser"><div><div class="eyebrow">EXPLORE THE CURRICULUM</div><p>Browse a detailed sample before starting your journey.</p></div><label><span class="sr-only">Browse sample roadmap</span><select id="roadmap-template-select"><option value="">My active journey</option>${TRACKS.map(t=>`<option value="${t.id}" ${v.examplePlan?.trackId===t.id?'selected':''}>${esc(t.name)} · ${t.modules.length} chapters · ${t.concepts.length} concepts</option>`).join('')}</select></label></section>
  <div class="goal-strip"><span class="eyebrow">${icon('flag')} ${sample?'SAMPLE':'JOURNEY'}</span>${sample?`<strong>${esc(j.title)}</strong><span class="badge sample">Preview only · Not activated</span>`:``}<select ${sample?'hidden':''} id="journey-select" aria-label="Select journey">${s.journeys.map(x=>`<option value="${x.id}" ${x.id===j.id?'selected':''}>${esc(x.title)}${x.status==='completed'?' · Completed':''}</option>`).join('')}</select>${badge(`Version ${j.version}`,'gold')}</div>
  ${!sample&&s.proposal?`<div class="proposal-banner"><div>${icon('spark')}<strong>A gentler pace is ready for review.</strong><p>${s.proposal.previous} → ${s.proposal.minutes} minutes/day. Your completed and in-progress work stays with you.</p></div>${btn('Review proposed changes','proposal',{primary:true,icon:'arrow'})}</div>`:''}
  <div class="graph-layout expansive-layout"><section class="paper graph-panel"><div class="graph-tools">${graphToolbar(v.view)}<span class="small-copy">${j.chapters.length} chapters · ${qs.length} activities</span></div><div class="graph-pagination"><span>Full branching roadmap · Solid: suggested prerequisite · Dashed: optional exploration</span></div>${v.view==='graph'?roadmapGraph(j,qs,ci):`<div class="chapter-list">${j.chapters.map((ch,i)=>`<button class="chapter-row ${ci===i?'selected':''}" data-action="chapter" data-id="${i}"><span class="chapter-numeral">${String(i+1).padStart(2,'0')}</span><div><small>CHAPTER ${i+1}</small><h3>${esc(ch.title)}</h3><p>${esc(ch.summary)}</p><div class="topic-tags">${(ch.topics||[]).map(t=>badge(t)).join('')}</div></div>${icon('chevron')}</button>`).join('')}</div>`}<div class="graph-legend"><span><i class="green-dot"></i>Completed activities</span><span><i class="red-dot"></i>Selected chapter</span><span><i class="gold-dot"></i>Ready to explore</span></div></section><aside class="detail-column"><section class="paper dossier"><div class="detail-title"><span class="eyebrow red-text">${icon('book')} CHAPTER DOSSIER</span>${badge(`№ ${ci+1}`,'gold')}</div><h2>${esc(c.title)}</h2><p>${esc(c.summary)}</p><div class="pathway-note"><strong>${esc(c.lane||'Study chapter')}</strong><p>${c.requires?.length?'Suggested first: '+c.requires.map(i=>esc(j.chapters[i].title)).join(' · '):'Start here — no prerequisite chapters.'}</p><small>Suggested order · Activities remain open for exploration.</small></div><div class="eyebrow">CONCEPTS IN THIS CHAPTER</div><div class="topic-tags">${(c.topics||[]).map(t=>badge(t)).join('')}</div><div class="chapter-progress"><div class="stat-caption"><span>Chapter activities</span><b>${cqs.filter(q=>q.status==='completed').length} / ${cqs.length}</b></div>${progress(cqs.filter(q=>q.status==='completed').length/cqs.length*100)}</div><div class="chapter-quests">${cqs.map(q=>`<button data-action="quest" data-id="${q.id}">${icon(q.status==='completed'?'check':'book')}<span><strong>${esc(q.title)}</strong><small>${q.minutes} min · +${q.xp} XP · ${q.status==='completed'?'Completed':q.type}</small></span>${icon('chevron')}</button>`).join('')}</div></section><section class="paper companion-note"><div class="eyebrow">${icon('spark')} ARCANA'S GUIDANCE</div><p>“A good roadmap gives you direction and room to breathe. We can always adjust the pace.”</p>${sample?btn('Personalize with Arcana','start-track',{id:j.trackId,icon:'spark'}):btn('Adjust my schedule','schedule',{icon:'clock'})}</section></aside></div>
  <div class="expedition-footer"><span>${icon('clock')} Pacing: <b>${j.minutes} min/day</b></span><span>${icon('flag')} Estimated journey: <b>${j.days} study days</b></span><span>${done} / ${qs.length} activities</span>${sample?btn('Start this sample roadmap','start-example',{icon:'flag',class:'small'}):btn(j.status==='completed'?'Journey completed':'Reflect & finish journey','finish-journey',{icon:'check',class:'small',disabled:j.status==='completed'})}</div>`;
}
export function progressPage(s){
  const server=s.mode==='server',name=s.profile?.displayName||'Minh',domains=server&&s.domains?.length?s.domains:TRACKS.map(track=>({id:track.id,name:track.name,icon:track.icon,color:track.color}));
  const complete=s.quests.filter(q=>q.status==='completed').length,earnedBadges=server?(s.achievements||[]):[{name:'First Steps',description:'Complete your first quest.'},{name:'Curious Mind',description:'Discover ten concepts.'},{name:'Branching Out',description:'Explore three fields.'}];
  return `${sectionHead('MILESTONES / YOUR PERSONAL CHRONICLE','A story of steady growth','Every experience leaves a little ink on the page.',badge(server?'Account profile':'Illustrative profile',server?'green':'sample'))}
  <section class="paper progress-hero"><div class="portrait-frame"><img src="/assets/minh.png" alt="${esc(name)}, a LifeOS learner"></div><div><div class="eyebrow red-text">${esc(name.toUpperCase())} · ${server?'LEARNER':'APPRENTICE SCRIBE'}</div><h2>Your adventure is unfolding.</h2><p>Activity earns experience. Understanding grows through reflection.</p><div class="progress-metrics"><div><strong>${levelFor(s.xp)}</strong><span>Character level</span></div><div><strong>${s.xp}</strong><span>Total XP</span></div><div><strong>${complete}</strong><span>Activities complete</span></div>${server?`<div><strong>${s.profile?.coins??0}</strong><span>Coins</span></div>`:''}</div>${progress(s.xp%100)}<p class="small-copy">${100-s.xp%100} XP until your next character level · ${s.dailyXp}/120 XP earned today</p></div></section>
  <section class="paper"><div class="panel-heading"><h2>${icon('trophy')} ${server?'Unlocked achievements':'Sample achievements'}</h2><span class="small-copy">${earnedBadges.length} collected</span></div><div class="achievement-list">${earnedBadges.map(item=>`<div>${icon('star')}<span><strong>${esc(item.name)}</strong><small>${esc(item.description||'A mark in your chronicle.')}</small></span>${item.unlockedAt?badge('Unlocked','green'):badge('Sample','gold')}</div>`).join('')||'<p>Complete quests and grow your knowledge to earn your first achievement.</p>'}</div></section>
  <div class="section-title"><div><div class="eyebrow">GROWTH HAS MANY FORMS</div><h2>Your domain chronicles</h2></div>${badge(server?'Server profile':'Sample observations',server?'green':'sample')}</div><div class="rank-grid">${domains.map(domain=>`<section class="paper rank-card" style="--domain-color:${domain.color}"><span class="rank-emblem">${icon(domain.icon||'tree')}</span><h3>${esc(domain.name)}</h3>${badge(s.ranks.find(r=>r.trackId===domain.id)?.rank||'Novice','gold')}<p>${server?'Current domain rank from your account.':'Illustrative signals within this field. Independent of activity XP.'}</p>${btn('Explore knowledge','knowledge-track',{id:domain.id,icon:'arrow',class:'text-button'})}</section>`).join('')}</div>
  <div class="two-columns"><section class="paper"><div class="panel-heading"><h2>${icon('star')} Collected milestones</h2></div><div class="achievement-list">${server?(s.milestones.length?s.milestones.map(item=>`<div>${icon('star')}<span><strong>${esc(item.name)}</strong><small>Reached ${esc(String(item.reachedAt||'').slice(0,10))}</small></span><span class="seal">✦</span></div>`).join(''):'<p>No milestones recorded yet.</p>'):[['book','The First Page','Begin a learning journey'],['flame','A Week of Curiosity','7 active days · sample history'],['tree','Branching Out','Explore connected fields of knowledge']].map(([i,t,d])=>`<div>${icon(i)}<span><strong>${t}</strong><small>${d}</small></span><span class="seal">✦</span></div>`).join('')}</div></section><section class="paper"><div class="panel-heading"><h2>${icon('pen')} Experience ledger</h2></div><div class="ledger">${s.ledger.slice(0,8).map(l=>`<div><span><strong>${esc(l.title)}</strong><small>${esc(l.date)}</small></span><b>+${l.xp} XP</b></div>`).join('')||'<p>Your account history is available as XP is earned.</p>'}</div></section></div>`;
}
export function settingsPage(s){const journey=activeJourney(s),server=s.mode==='server',name=s.profile?.displayName||'Minh',owned=new Set((s.inventory||[]).map(item=>item.id)),slot={AVATAR:'avatarItemId',FRAME:'frameItemId',TITLE:'titleItemId'},cosmetics=server?`<section class="paper settings-panel"><div class="section-title"><h2>${icon('star')} Keepsakes</h2><span class="badge gold">${s.profile?.coins??0} Coins</span></div><p class="small-copy">Choose an avatar, frame or title. These items change appearance only.</p><div class="inventory-grid">${(s.inventoryCatalog||[]).map(item=>{const has=owned.has(item.id),field=slot[item.category],equipped=field&&s.profile?.[field]===item.id;return `<article class="inventory-card"><strong>${esc(item.name)}</strong><small>${esc(item.category.replaceAll('_',' '))}${item.rarity?' · '+esc(item.rarity):''}</small><p>${esc(item.description||'A keepsake for your grimoire.')}</p>${field?(has?equipped?badge('Equipped','green'):btn('Equip','equip-item',{id:item.id}):btn(item.priceCoins?`Unlock · ${item.priceCoins} Coins`:'Unlock','unlock-item',{id:item.id,primary:true})):badge(has?'Owned':item.priceCoins?`${item.priceCoins} Coins`:'Keepsake',has?'gold':'')}</article>`;}).join('')}</div></section>`:'',pushPanel=server?`<section class="paper settings-panel"><h2>${icon('clock')} Daily reminders</h2><p>Get one gentle reminder when you have an active journey and no completed activity for your local day. You can turn it off at any time.</p>${s.pushEnabled?btn('Disable daily reminder','disable-push'):btn('Enable daily reminder','enable-push',{primary:true,icon:'clock'})}<p class="small-copy">Your browser asks for notification permission only after you choose Enable.</p></section>`:'';return `${sectionHead('YOUR SANCTUARY / PREFERENCES','Make this grimoire yours','A little control over how you learn and what your companion remembers.')}
  <div class="settings-layout"><section class="paper settings-panel"><h2>${icon('settings')} Learning preferences</h2>${[['streak','Show learning streak','A gentle reminder of your rhythm. Hiding it never changes your progress.'],['inference','Allow conversation observations','Demo preference only. This companion never infers real knowledge from your messages.'],['reducedMotion','Reduce motion','Keep transitions and decorative motion to a minimum.']].map(([key,title,description])=>`<label class="setting-row"><span><strong>${title}</strong><small>${description}</small></span><input type="checkbox" role="switch" data-pref="${key}" ${s.preferences[key]?'checked':''} ${server?'disabled':''}></label>`).join('')}${journey?`<div class="setting-row"><span><strong>Daily study budget</strong><small>Changes are previewed before you apply them.</small></span>${btn(`${journey.minutes} min · Adjust`,'schedule',{icon:'clock',class:'small'})}</div>`:''}</section>
  ${server?'':`<section class="paper settings-panel"><div class="section-title"><h2>${icon('book')} Memory core</h2>${badge('Local only','green')}</div><p class="small-copy">Notes you choose to keep. Sample replies do not use these notes to assess you.</p><div class="memory-list">${s.memories.length?s.memories.map(m=>`<div><span><strong>${esc(m.text)}</strong><small>${esc(m.source)}</small></span><button class="icon-button" data-action="delete-memory" data-id="${m.id}" aria-label="Delete memory: ${esc(m.text)}">${icon('trash')}</button></div>`).join(''):'<p>Your memory core is empty. Add a note below.</p>'}</div><form id="memory-form" class="memory-form"><label class="sr-only" for="memory-input">New memory</label><input id="memory-input" name="memory" maxlength="240" placeholder="Something you want to remember…" required><button class="btn" type="submit">${icon('plus')} Add note</button></form></section>`}
  ${cosmetics}${pushPanel}<section class="paper settings-panel"><h2>${icon('shield')} ${server?'Your account':'About this demo'}</h2><p>${server?'Your learning progress, Companion chat, and accepted roadmaps are handled by the server. Live AI features require a configured Gemini key and an available weekly budget.':'This is an interactive prototype with prepared learning content. Arcana uses scripted responses, and roadmaps are assembled from '+TRACKS.length+' detailed curriculum templates.'}</p><div class="info-grid"><div><small>PROFILE</small><strong>${esc(name)}${server?' · account':' · sample learner'}</strong></div><div><small>STORAGE</small><strong>${server?'LifeOS account':'This browser only'}</strong></div><div><small>LANGUAGE</small><strong>English</strong></div><div><small>AI CONNECTION</small><strong>${server?'Optional · server Gemini key':'Simulated · no API key'}</strong></div></div></section>
  ${server?'':`<section class="paper settings-panel reset-panel"><h2>${icon('reset')} Open a fresh page</h2><p>Restore the original sample profile, conversations, quests, and roadmap for another presentation. This removes changes made in this browser.</p>${btn('Reset demo data','reset',{icon:'reset'})}</section>`}</div>`;}
