import {z} from 'zod';
import type {AIProvider,AIResult} from './provider.ts';

const questSchema=z.object({title:z.string().trim().min(3).max(120),type:z.enum(['Learn','Practice','Assessment','Project']),difficulty:z.enum(['A','B','C','D']),minutes:z.number().int().min(5).max(120),prompt:z.string().trim().min(12).max(600),steps:z.array(z.string().trim().min(2).max(180)).min(2).max(6),description:z.string().trim().min(5).max(400),topic:z.string().trim().min(2).max(120)}).strict();
const chapterSchema=z.object({title:z.string().trim().min(3).max(120),summary:z.string().trim().min(12).max(600),lane:z.string().trim().min(2).max(80),topics:z.array(z.string().trim().min(2).max(100)).min(2).max(8),requires:z.array(z.number().int().min(0).max(9)).max(9),optional:z.boolean(),quests:z.array(questSchema).min(2).max(4)}).strict();
export const CustomRoadmapSchema=z.object({title:z.string().trim().min(3).max(160),domainName:z.string().trim().min(2).max(100),chapters:z.array(chapterSchema).min(6).max(10)}).strict().superRefine((roadmap,ctx)=>{
 roadmap.chapters.forEach((chapter,index)=>{if(new Set(chapter.requires).size!==chapter.requires.length)ctx.addIssue({code:'custom',path:['chapters',index,'requires'],message:'Chapter requirements must be unique.'});if(chapter.requires.some(required=>required>=index))ctx.addIssue({code:'custom',path:['chapters',index,'requires'],message:'Chapters may only depend on earlier chapters.'});});
});
const requestSchema=z.object({topic:z.string().trim().min(2).max(120),goal:z.string().trim().min(3).max(240),experienceLevel:z.enum(['beginner','some','experienced']),minutesPerDay:z.number().int().min(15).max(120)}).strict();
const jsonSchema={type:'OBJECT',properties:{title:{type:'STRING'},domainName:{type:'STRING'},chapters:{type:'ARRAY',minItems:6,maxItems:10,items:{type:'OBJECT',properties:{title:{type:'STRING'},summary:{type:'STRING'},lane:{type:'STRING'},topics:{type:'ARRAY',items:{type:'STRING'}},requires:{type:'ARRAY',items:{type:'INTEGER'}},optional:{type:'BOOLEAN'},quests:{type:'ARRAY',minItems:2,maxItems:4,items:{type:'OBJECT',properties:{title:{type:'STRING'},type:{type:'STRING',enum:['Learn','Practice','Assessment','Project']},difficulty:{type:'STRING',enum:['A','B','C','D']},minutes:{type:'INTEGER'},prompt:{type:'STRING'},steps:{type:'ARRAY',items:{type:'STRING'}},description:{type:'STRING'},topic:{type:'STRING'}},required:['title','type','difficulty','minutes','prompt','steps','description','topic'],propertyOrdering:['title','type','difficulty','minutes','prompt','steps','description','topic']}}},required:['title','summary','lane','topics','requires','optional','quests'],propertyOrdering:['title','summary','lane','topics','requires','optional','quests']}}},required:['title','domainName','chapters'],propertyOrdering:['title','domainName','chapters']};
const slug=(value:string)=>value.normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,64)||'custom-learning';
const xpFor=(type:string,difficulty:string)=>({Learn:10,Practice:15,Assessment:20,Project:25}[type]??10)+({A:0,B:2,C:5,D:8}[difficulty]??0);
export async function generateCustomRoadmap(provider:AIProvider,requestInput:unknown,catalog:Array<{name:string;description?:string;concepts?:string[]}>,signal?:AbortSignal){
 const request=requestSchema.parse(requestInput),reference=catalog.slice(0,40).map(domain=>`${domain.name}: ${domain.description||''}. Concepts: ${(domain.concepts||[]).slice(0,30).join(', ')}`).join('\n');
 const output=await provider.generateStructured<unknown>({purpose:'ROADMAP',schema:jsonSchema,prompt:`Design a detailed, beginner-appropriate learning roadmap for the user's subject. Ground overlapping topics in this canonical catalog and add new concepts only where needed. Build 6 to 10 ordered chapters, each with 2 to 4 small activities. Use only the allowed activity types. Keep every activity within the user's daily time budget. Each chapter's requires list may reference only earlier chapter indexes and must be acyclic. Each activity needs actionable steps. Do not include XP or external URLs; the server supplies rewards and resources. Match the user's goal and experience.\nSUBJECT: ${request.topic}\nGOAL: ${request.goal}\nEXPERIENCE: ${request.experienceLevel}\nMINUTES PER DAY: ${request.minutesPerDay}\nCANONICAL LEARNING CATALOG:\n${reference}`},signal);
 const parsed=CustomRoadmapSchema.safeParse(output.data);if(!parsed.success)throw new Error('The generated roadmap did not pass validation.');
 const chapters=parsed.data.chapters.map(chapter=>({...chapter,quests:chapter.quests.map(quest=>{if(quest.minutes>request.minutesPerDay)throw new Error('An activity exceeds the selected daily time budget.');return {...quest,xp:xpFor(quest.type,quest.difficulty),checks:[],resource:'#'};})}));
 const totalMinutes=chapters.flatMap(chapter=>chapter.quests).reduce((sum,quest)=>sum+quest.minutes,0),trackId=slug(parsed.data.domainName),days=Math.ceil(totalMinutes/request.minutesPerDay),draft={id:crypto.randomUUID(),trackId,trackName:parsed.data.domainName,title:parsed.data.title,goal:request.goal,minutes:request.minutesPerDay,totalMinutes,minutesPerDay:request.minutesPerDay,experience:request.experienceLevel,experienceLevel:request.experienceLevel,days,chapters};
 return {draft,model:output.model,...(output.usage?{usage:output.usage}:{})};
}
